version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6378:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - redis

  django:
    build:
      context: .
      dockerfile: etc/Dockerfile_django
    container_name: django_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  aio_bot:
    build:
      context: .
      dockerfile: etc/Dockerfile_bot
    container_name: aio_bot
    restart: always
    depends_on:
      - django
      - redis
      - db
    ports:
      - "8082:8080"

  celery_worker:
    build:
      context: .
      dockerfile: etc/Dockerfile_worker
    container_name: "celery_worker"
    restart: always
    depends_on:
      - db
      - django
      - redis
      - aio_bot

  celery_beat:
    build:
      context: .
      dockerfile: etc/Dockerfile_beat
    container_name: "celery_beat"
    restart: always
    depends_on:
      - db
      - django
      - celery_worker
      - redis
      - aio_bot

volumes:
  pgdata:
