FROM python:3.12-slim

WORKDIR /todo_TG_bot

COPY etc/req_bot.txt .
RUN pip install --no-cache-dir -r req_bot.txt

COPY aio_bot aio_bot
COPY config.py .
COPY .env .

CMD ["python3", "aio_bot/main.py"]
