FROM python:3.12-slim

WORKDIR /todo_TG_bot/app

COPY etc/req_worker.txt .
RUN pip install -r req_worker.txt

COPY app .
COPY config.py /todo_TG_bot
COPY .env /todo_TG_bot

CMD ["celery", "-A", "app", "worker", "-l", "info"]
