# Generated by Django 5.2.1 on 2025-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
